### ISSUE TITLE
开始

### ISSUE THREAD

**Issue by wsp03** [Kindle-deep/hugo-theme-Kenny#2]
hexo渲染太慢，但是butterfly我魔改的又不想放弃，但是自己没本事迁移，所以只好来白嫖你的了😁😁😁。还是在店长群里看到的。
当然建议您可以像butterfly一样使用一个issue用来添加示例网站。
我下午回去就入坑，添加友联🤗

**Comment by Kindle-deep** [comment]
哈哈，好的，会考虑一下的

**Comment by TY10909** [comment]
close
